<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://nav.no/melding/virksomhet/dokdistfordeling"
		   xmlns:dokdistfordeling="http://nav.no/melding/virksomhet/dokdistfordeling">

	<xs:element name="distribuerForsendelse" type="dokdistfordeling:DistribuerForsendelse"/>

	<xs:complexType name="DistribuerForsendelse">
		<xs:sequence>
			<xs:element name="distribusjonbestilling" type="dokdistfordeling:Distribusjonbestilling"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="Distribusjonbestilling">
		<xs:sequence>
			<xs:element name="bestillingsId" type="dokdistfordeling:nonEmptyStringNoBlanks">
				<xs:annotation>
					<xs:documentation>Forsendelsens bestillingsId. GUID som skapes av bestiller. Kan ikke inneholde blank eller
						space.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="batchId" type="dokdistfordeling:nonEmptyStringNoBlanks" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Identifiserer batch forsendelsen inngår i. Lar bestiller identifisere forsendelser som
						hører sammen. Fritekst, og konsument må selv vurdere hva som er hensiktsmessige verdier.
						Kan ikke inneholde blank eller space.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="bestillendeFagsystem" type="dokdistfordeling:nonEmptyStringNoBlanks">
				<xs:annotation>
					<xs:documentation>Fagsystem som bestiller distribusjon.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="tema" type="dokdistfordeling:nonEmptyStringNoBlanks">
				<xs:annotation>
					<xs:documentation>Tema som forsendelsen tilhører. Se dokumentdistribusjon-kodeverk K_FAGOMRADE for gyldige
						verdier
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="forsendelseTittel" type="dokdistfordeling:nonEmptyStringNoBlanks" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Skal kun benyttes ved behov for "fritekst" tittel (når det ikke er mulig å
						forhåndsklassifisere tittel på dokumenttypeId som distribueres,
						bør kun være unntaksvis eksempelvis for InfoTrygd-dokumenter). Hvis ikke satt hentes hoveddokumentets
						tittel fra dokumentkatalogen
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="arkivInformasjon" type="dokdistfordeling:ArkivInformasjon" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Informasjon om hvor forsendelsen er arkivert. Muliggjør statusoppdatering i Joark og
						automatisk returposthåndtering.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="mottaker" type="dokdistfordeling:Aktoer">
				<xs:annotation>
					<xs:documentation>Struktur for å beskrive mottaker av forsendelsen. Inneholder enten Organisasjon, Person
						eller Samhandler.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="bruker" type="dokdistfordeling:Aktoer">
				<xs:annotation>
					<xs:documentation>Struktur for å beskrive sakspart forsendelsen gjelder. Inneholder enten Organisasjon, Person eller Samhandler
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="adresse" type="dokdistfordeling:Adresse" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Struktur for å beskrive postadresse. Inneholder enten norskPostadresse eller
						utenlandskPostadresse. Påkrevd hvis mottaker er samhandler, ellers hentes adresse fra fellesregistre
						hvis ikke satt.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="dokumentProdApp" type="dokdistfordeling:nonEmptyStringNoBlanks">
				<xs:annotation>
					<xs:documentation>Applikasjon som har produsert dokumentet (for sporing og feilsøking).</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="dokumenter" type="dokdistfordeling:DokumentInformasjonListe">
				<xs:annotation>
					<xs:documentation>Liste med dokumenter som skal inngå i forsendelsen.
						Må inneholde minst ett dokument, og ett av dokumentene skal ha tilknyttetSom lik "HOVEDDOKUMENT".
					</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType abstract="true" name="Adresse"/>
	<xs:complexType abstract="true" name="Aktoer"/>

	<xs:complexType name="NorskPostadresse">
		<xs:annotation>
			<xs:documentation>Postadresse i Norge.</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="dokdistfordeling:Adresse">
				<xs:sequence>
					<xs:element name="adresselinje1" type="xs:string" minOccurs="0">
						<xs:annotation>
							<xs:documentation>Inneholder del av adresse som skal presenteres på egen linje</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="adresselinje2" type="xs:string" minOccurs="0">
						<xs:annotation>
							<xs:documentation>Inneholder del av adresse som skal presenteres på egen linje</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="adresselinje3" type="xs:string" minOccurs="0">
						<xs:annotation>
							<xs:documentation>Inneholder del av adresse som skal presenteres på egen linje</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="postnummer" type="dokdistfordeling:nonEmptyStringNoBlanks">
						<xs:annotation>
							<xs:documentation>Gyldig norsk postnummer</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="poststed" type="dokdistfordeling:nonEmptyStringNoBlanks">
						<xs:annotation>
							<xs:documentation>Gyldig norsk poststed</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="land" type="dokdistfordeling:ISO3166-1-alpha-2">
						<xs:annotation>
							<xs:documentation>Gyldig ISO 3166-1 alpha-2 kode. To bokstavs landkode. Eks: NO for Norge
							</xs:documentation>
						</xs:annotation>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="UtenlandskPostadresse">
		<xs:annotation>
			<xs:documentation>Postadresse i utlandet.</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="dokdistfordeling:Adresse">
				<xs:sequence>
					<xs:element name="adresselinje1" type="xs:string">
						<xs:annotation>
							<xs:documentation>Inneholder del av adresse som skal presenteres på egen linje</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="adresselinje2" type="xs:string" minOccurs="0">
						<xs:annotation>
							<xs:documentation>Inneholder del av adresse som skal presenteres på egen linje</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="adresselinje3" type="xs:string" minOccurs="0">
						<xs:annotation>
							<xs:documentation>Inneholder del av adresse som skal presenteres på egen linje</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="land" type="dokdistfordeling:ISO3166-1-alpha-2">
						<xs:annotation>
							<xs:documentation>Gyldig ISO 3166-1 alpha-2 kode. To bokstavs landkode. Eks: NO for Norge
							</xs:documentation>
						</xs:annotation>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="AktoerId">
		<xs:complexContent>
			<xs:extension base="dokdistfordeling:Aktoer">
				<xs:sequence>
					<xs:element name="aktoerId" type="dokdistfordeling:nonEmptyStringNoBlanks">
						<xs:annotation>
							<xs:documentation>aktørid for person som er mottaker av forsendelsen.
							</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="navn" type="dokdistfordeling:nonEmptyStringNoBlanks" minOccurs="0">
						<xs:annotation>
							<xs:documentation>Navn på personen som er mottaker av forsendelsen. Hentes fra fellesregistre hvis
								ikke satt.
							</xs:documentation>
						</xs:annotation>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="Organisasjon">
		<xs:complexContent>
			<xs:extension base="dokdistfordeling:Aktoer">
				<xs:sequence>
					<xs:element name="orgnummer">
						<xs:annotation>
							<xs:documentation>orgnummer (9 siffer) til organisasjonen som er mottaker av forsendelsen.
							</xs:documentation>
						</xs:annotation>
						<xs:simpleType>
							<xs:restriction base="xs:token">
								<xs:pattern value="\d{9}"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:element>
					<xs:element name="navn" type="dokdistfordeling:nonEmptyStringNoBlanks" minOccurs="0">
						<xs:annotation>
							<xs:documentation>Navn på organisasjonen som er mottaker av forsendelsen. Hentes fra fellesregistre
								hvis ikke satt.
							</xs:documentation>
						</xs:annotation>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="Person">
		<xs:complexContent>
			<xs:extension base="dokdistfordeling:Aktoer">
				<xs:sequence>
					<xs:element name="personidentifikator">
						<xs:annotation>
							<xs:documentation>Fødselsnummer/d-nummer (11 siffer) til personen som er mottaker av forsendelsen.
							</xs:documentation>
						</xs:annotation>
						<xs:simpleType>
							<xs:restriction base="xs:token">
								<xs:pattern value="\d{11}"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:element>
					<xs:element name="navn" type="dokdistfordeling:nonEmptyStringNoBlanks" minOccurs="0">
						<xs:annotation>
							<xs:documentation>Navn på personen som er mottaker av forsendelsen. Hentes fra fellesregistre hvis
								ikke satt.
							</xs:documentation>
						</xs:annotation>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="Samhandler">
		<xs:complexContent>
			<xs:extension base="dokdistfordeling:Aktoer">
				<xs:sequence>
					<xs:element name="samhandleridentifikator" type="dokdistfordeling:nonEmptyStringNoBlanks">
						<xs:annotation>
							<xs:documentation>Identifikator til samhandler som er mottaker av forsendelsen.
							</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="navn" type="dokdistfordeling:nonEmptyStringNoBlanks">
						<xs:annotation>
							<xs:documentation>Navn på samhandler som er mottaker av forsendelsen
							</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="samhandlerkategori" type="dokdistfordeling:nonEmptyStringNoBlanks">
						<xs:annotation>
							<xs:documentation>Samhandlerkategori for mottaker av forsendelsen. Gyldig verdi: "HPR"
								(Helsepersonellregister).
							</xs:documentation>
						</xs:annotation>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="ArkivInformasjon">
		<xs:sequence>
			<xs:element name="arkivSystem" type="dokdistfordeling:nonEmptyStringNoBlanks">
				<xs:annotation>
					<xs:documentation>Angivelse av hvilket arkivsystem dokumentet er arkivert i.
						Se dokumentdistribusjon-kodeverk K_ARKIV_SYSTEM. MIDL_BREVLAGER skal ikke benyttes.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="arkivId" type="dokdistfordeling:nonEmptyStringNoBlanks">
				<xs:annotation>
					<xs:documentation>Angivelse av dokumentets arkivnøkkel/id (journalpostid).</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="DokumentInformasjonListe">
		<xs:sequence>
			<xs:element name="dokumentInformasjon" type="dokdistfordeling:DokumentInformasjon" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>DokumentInformasjon-objekt som beskriver dokument som skal være del av forsendelsen. Kan være flere dokumenter i listen
					</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="DokumentInformasjon">
		<xs:sequence>
			<xs:element name="dokumenttypeId" type="dokdistfordeling:nonEmptyStringNoBlanks">
				<xs:annotation>
					<xs:documentation>Nøkkel for oppslag i Dokumentkatalogen.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="dokumentObjektReferanse" type="dokdistfordeling:nonEmptyStringNoBlanks">
				<xs:annotation>
					<xs:documentation>Nøkkel (bucket key) til dokumentet i dokumentdistribusjons S3. Må være globalt unik, GUID
						anbefales.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="tilknyttetSom" type="dokdistfordeling:nonEmptyStringNoBlanks">
				<xs:annotation>
					<xs:documentation>Angir om dokument er "HOVEDDOKUMENT" eller "VEDLEGG". Kun ett dokument skal være
						tilknyttet forsendelsen som hoveddokument.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="arkivDokumentInfoId" type="dokdistfordeling:nonEmptyStringNoBlanks" minOccurs="0">
				<xs:annotation>
					<xs:documentation>dokumentId i arkivet. Påkrevd hvis Input.arkivInformasjon er satt
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="rekkefolge" type="xs:int">
				<xs:annotation>
					<xs:documentation>
						Dokumentets plassering i forsendelsen. Skal være 1 dersom tilknyttetSom = "HOVEDDOKUMENT".
						Skal være > 1 dersom tilknyttetSom = "VEDLEGG".
					</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:simpleType name="nonEmptyStringNoBlanks">
		<xs:restriction base="xs:token">
			<xs:minLength value="1"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ISO3166-1-alpha-2">
		<xs:restriction base="xs:token">
			<xs:pattern value="([A-Z]{2})|(\?\?\?)"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>