spring.main.banner_mode=off

# server
server.shutdown=graceful
server.error.include-message=always

# actuators
management.endpoints.web.exposure.include=prometheus,health
management.endpoint.health.group.liveness.include=jms

# camel
camel.springboot.use-mdc-logging=true
camel.springboot.jmx-enabled=false