spring.main.banner_mode=off

# server
server.shutdown=graceful
spring.web.error.include-message=always

# actuators
management.endpoints.web.exposure.include=prometheus,health
management.endpoint.health.group.liveness.include=camelHealth
management.endpoint.health.show-components=always
management.endpoint.health.show-details=always
# Fjern metrikker gitt av appd
management.metrics.enable.http.client.requests=false
# Aktivering av helsepunkt for lokal kjoering / i tester
management.endpoint.health.probes.enabled=true

# camel
camel.mdc.enabled=true
camel.main.jmx-enabled=false

spring.http.codecs.max-in-memory-size=200MB
spring.jackson.deserialization.fail-on-null-for-primitives=false
spring.jackson.mapper.accept-case-insensitive-properties=true

# circuitbreaker
resilience4j.circuitbreaker.configs.default.record-exceptions=no.nav.dokdistfordeling.exception.technical.AbstractDokdistfordelingTechnicalException
resilience4j.circuitbreaker.configs.default.ignore-exceptions=no.nav.dokdistfordeling.exception.functional.AbstractDokdistfordelingFunctionalException
resilience4j.circuitbreaker.instances.dokdistadmin.base-config=default
resilience4j.circuitbreaker.instances.dokdistkanal.base-config=default
resilience4j.circuitbreaker.instances.dokarkiv.base-config=default
resilience4j.circuitbreaker.instances.dokmet.base-config=default
resilience4j.circuitbreaker.instances.pdl.base-config=default
resilience4j.circuitbreaker.instances.regoppslag.base-config=default
resilience4j.circuitbreaker.instances.safgraphql.base-config=default
resilience4j.circuitbreaker.instances.safhentdokument.base-config=default

# retry
resilience4j.retry.configs.default.retry-exceptions=no.nav.dokdistfordeling.exception.technical.AbstractDokdistfordelingTechnicalException
resilience4j.retry.configs.default.ignore-exceptions=no.nav.dokdistfordeling.exception.functional.AbstractDokdistfordelingFunctionalException,\
  no.nav.dokdistfordeling.exception.functional.DokdistkanalMappingException
resilience4j.retry.instances.dokdistadmin.base-config=default
resilience4j.retry.instances.dokdistkanal.base-config=default
resilience4j.retry.instances.dokarkiv.base-config=default
resilience4j.retry.instances.dokmet.base-config=default
resilience4j.retry.instances.pdl.base-config=default
resilience4j.retry.instances.regoppslag.base-config=default
resilience4j.retry.instances.safgraphql.base-config=default
resilience4j.retry.instances.safhentdokument.base-config=default

# Database
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.query.in_clause_parameter_padding=true
spring.jpa.properties.hibernate.jdbc.fetch_size=100