no.nav.security.jwt.issuer.entra.proxy-url=${HTTP_PROXY}
no.nav.security.jwt.issuer.entra.accepted-audience=${AZURE_APP_CLIENT_ID},${SAF_ENTRA_APP_CLIENT_ID}
no.nav.security.jwt.issuer.entra.discovery-url=${AZURE_APP_WELL_KNOWN_URL}