kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: {{ APP_NAME }}
  namespace: teamdokumenthandtering
  labels:
    team: teamdokumenthandtering
spec:
  env:
    - name: SECURITY_TOKEN_SERVICE_TOKEN_URL
      value: {{ SECURITY_TOKEN_SERVICE_TOKEN_URL }}
    - name: NO_NAV_SECURITY_JWT_ISSUER_RESTSTS_DISCOVERYURL
      value: {{ NO_NAV_SECURITY_JWT_ISSUER_RESTSTS_DISCOVERYURL }}
    - name: NO_NAV_SECURITY_JWT_ISSUER_RESTSTS_ACCEPTED_AUDIENCE
      value: {{ NO_NAV_SECURITY_JWT_ISSUER_RESTSTS_ACCEPTED_AUDIENCE }}
    - name: MQGATEWAY01_CHANNEL_SECURENAME
      value: {{ MQGATEWAY01_CHANNEL_SECURENAME }}
    - name: MQGATEWAY01_HOSTNAME
      value: {{ MQGATEWAY01_HOSTNAME }}
    - name: MQGATEWAY01_PORT
      value: "{{ MQGATEWAY01_PORT }}"
    - name: MQGATEWAY01_NAME
      value: {{ MQGATEWAY01_NAME }}
    - name: DOKDISTFORDELING_QDIST008_DIST_FORSENDELS_QUEUENAME
      value: {{ DOKDISTFORDELING_QDIST008_DIST_FORSENDELS_QUEUENAME }}
    - name: DOKDISTFORDELING_QDIST008_FUNK_FEIL_QUEUENAME
      value: {{ DOKDISTFORDELING_QDIST008_FUNK_FEIL_QUEUENAME }}
    - name: DOKDISTSENTRALPRINT_QDIST009_DIST_S_PRINT_QUEUENAME
      value: {{ DOKDISTSENTRALPRINT_QDIST009_DIST_S_PRINT_QUEUENAME }}
    - name: DOKDISTDITTNAV_QDIST010_DIST_DITT_NAV_QUEUENAME
      value: {{ DOKDISTDITTNAV_QDIST010_DIST_DITT_NAV_QUEUENAME }}
    - name: DOKDISTDPI_QDIST011_DIST_TIL_DPI_QUEUENAME
      value: {{ DOKDISTDPI_QDIST011_DIST_TIL_DPI_QUEUENAME }}
    - name: DOKDISTFORDELING_QDIST012_HENT_DOK_JOARK_QUEUENAME
      value: {{ DOKDISTFORDELING_QDIST012_HENT_DOK_JOARK_QUEUENAME }}
    - name: DOKDISTFORDELING_QDIST012_FUNK_FEIL_QUEUENAME
      value: {{ DOKDISTFORDELING_QDIST012_FUNK_FEIL_QUEUENAME }}
    - name: DOKDISTEFORMIDLING_QDIST013_DIST_TRYGDERETTEN_QUEUENAME
      value: {{ DOKDISTEFORMIDLING_QDIST013_DIST_TRYGDERETTEN_QUEUENAME }}
    - name: DOKDISTDPO_QDIST015_DIST_TIL_DPO_QUEUENAME
      value: {{ DOKDISTDPO_QDIST015_DIST_TIL_DPO_QUEUENAME }}
    - name: DOKDISTDPV_QDIST016_DIST_TIL_DPV_QUEUENAME
      value: {{ DOKDISTDPV_QDIST016_DIST_TIL_DPV_QUEUENAME }}
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: "deployment.environment.name={{ ENVIRONMENT }}"
    - name: DOKDISTFORDELING_ENDPOINTS_DOKMET_URL
      value: {{ DOKDISTFORDELING_ENDPOINTS_DOKMET_URL }}
    - name: DOKDISTFORDELING_ENDPOINTS_DOKARKIV_SCOPE
      value: {{ DOKDISTFORDELING_ENDPOINTS_DOKARKIV_SCOPE }}
    - name: DOKDISTFORDELING_ENDPOINTS_DOKARKIV_URL
      value: {{ DOKDISTFORDELING_ENDPOINTS_DOKARKIV_URL }}
    - name: DOKDISTFORDELING_ENDPOINTS_DOKDISTADMIN_SCOPE
      value: {{ DOKDISTFORDELING_ENDPOINTS_DOKDISTADMIN_SCOPE }}
    - name: DOKDISTFORDELING_ENDPOINTS_DOKDISTADMIN_URL
      value: {{ DOKDISTFORDELING_ENDPOINTS_DOKDISTADMIN_URL }}
    - name: DOKDISTFORDELING_ENDPOINTS_DOKDISTKANAL_SCOPE
      value: {{ DOKDISTFORDELING_ENDPOINTS_DOKDISTKANAL_SCOPE }}
    - name: DOKDISTFORDELING_ENDPOINTS_DOKDISTKANAL_URL
      value: {{ DOKDISTFORDELING_ENDPOINTS_DOKDISTKANAL_URL }}
    - name: DOKDISTFORDELING_ENDPOINTS_PDL_SCOPE
      value: {{ DOKDISTFORDELING_ENDPOINTS_PDL_SCOPE }}
    - name: DOKDISTFORDELING_ENDPOINTS_PDL_URL
      value: {{ DOKDISTFORDELING_ENDPOINTS_PDL_URL }}
    - name: DOKDISTFORDELING_ENDPOINTS_REGOPPSLAG_URL
      value: {{ DOKDISTFORDELING_ENDPOINTS_REGOPPSLAG_URL }}
    - name: DOKDISTFORDELING_ENDPOINTS_REGOPPSLAG_SCOPE
      value: {{ DOKDISTFORDELING_ENDPOINTS_REGOPPSLAG_SCOPE }}
    - name: DOKDISTFORDELING_ENDPOINTS_SAF_SCOPE
      value: {{ DOKDISTFORDELING_ENDPOINTS_SAF_SCOPE }}
    - name: DOKDISTFORDELING_ENDPOINTS_SAF_URL
      value: {{ DOKDISTFORDELING_ENDPOINTS_SAF_URL }}
    - name: DOKDISTMELLOMLAGER_PROJECTID
      value: {{ DOKDISTMELLOMLAGER_PROJECTID }}
    - name: DOKDISTMELLOMLAGER_BUCKET
      value: {{ DOKDISTMELLOMLAGER_BUCKET }}
    - name: DOKDISTMELLOMLAGER_KEYRING
      value: {{ DOKDISTMELLOMLAGER_KEYRING }}
    - name: DOKDISTMELLOMLAGER_KEYID
      value: {{ DOKDISTMELLOMLAGER_KEYID }}
  image: {{ image }}
  ingresses:
    {{#each INGRESSES}}
       - {{this }}
      {{/each}}
  liveness:
    path: /actuator/health/liveness
    port: 8080
    initialDelay: 30
    failureThreshold: 10
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /actuator/health/readiness
    port: 8080
    initialDelay: 30
    timeout: 3
  replicas:
    min: {{ MIN_REPLICAS }}
    max: {{ MAX_REPLICAS }}
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 3Gi
    requests:
      cpu: 20m
      memory: 1Gi
  vault:
    enabled: true
    paths:
      - kvPath: {{ SRVDOKDISTFORDELING }}
        mountPath: /var/run/secrets/nais.io/srvdokdistfordeling
  envFrom:
    - secret: {{ DOKDISTFORDELING_NAIS_SECRETS }}
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
          - "azp_name"
  accessPolicy:
    inbound:
      rules:
    {{#each ENTRA_ID_PREAUTH}}
        - application: {{app}}
          namespace: {{namespace}}
          cluster: {{cluster}}
    {{/each}}
  webproxy: true
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
    autoInstrumentation:
      enabled: true
      runtime: java
      destinations:
        - id: "elastic-apm"